services:
  - type: web
    name: stockthai
    runtime: node
    buildCommand: npm install --cache /tmp/npm-cache --no-fund
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
    plan: free
